algoritmo "antecessor e sucessor"
// Função :
// Autor :
// Data : 08/10/2024
// Seção de Declarações 
var
  numero:inteiro
  antecessor:inteiro
  sucessor: inteiro
inicio
// Seção de Comandos
Escreva("Digite um número para saber seu antecessor e seu sucessor: ")
Leia(numero)
antecessor <- numero-1
sucessor <- numero+1
Escreval(" O antecessor de ",numero, " é igual a ", antecessor, ".")
Escreva(" O sucessor de ",numero, " é igual a ", sucessor, ".")
fimalgoritmo
