algoritmo "dobro e terça"
// Função :
// Autor :
// Data : 08/10/2024
// Seção de Declarações 
var
   numero: real
   dobro: real
   terca: real
inicio
// Seção de Comandos
Escreva("Digite um número para saber seu dobro e sua terça parte: ")
Leia(numero)
dobro <- numero*2
terca <- numero/3
Escreval("O dobro de ",numero, " é igual a ", dobro, ".")
Escreva("A terça parte de ",numero, " é igual a ", terca, ".")
fimalgoritmo
